on: push
jobs:
  my_job:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:light
    steps:
      - run: rm -rf .terraform
      - run: terraform --version
      - run: terraform init
      - run: terraform validate
